name: test
on: [push]
jobs:
  test-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.1'
      - run: bundle exec rake test